# Generated by Django 2.1.4 on 2018-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Khach_hang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(blank=True, max_length=264)),
                ('ten_dang_nhap', models.CharField(blank=True, max_length=50)),
                ('mat_khau', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=264)),
                ('email', models.EmailField(blank=True, max_length=264)),
                ('dia_chi', models.CharField(blank=True, max_length=264)),
            ],
            options={
                'db_table': 'KhachHang',
            },
        ),
    ]
